// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOIn4tAWtmTwstQx5swxaYLoWAaBs_tpE',
    appId: '1:935482127807:web:0c0ea000b35af20c3f5d0a',
    messagingSenderId: '935482127807',
    projectId: 'auradb-21288',
    authDomain: 'auradb-21288.firebaseapp.com',
    storageBucket: 'auradb-21288.firebasestorage.app',
    measurementId: 'G-M1H3PBYW50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuAHuBBPhSfCKjMoukYf-KkC_j0HrPRo8',
    appId: '1:935482127807:android:2c12ae50978399e53f5d0a',
    messagingSenderId: '935482127807',
    projectId: 'auradb-21288',
    storageBucket: 'portfolio-1952e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMNfTlo8wNiQevo509DuB1-2CNtyu8vWQ',
    appId: '1:935482127807:ios:0d2a5a00e2db12603f5d0a',
    messagingSenderId: '935482127807',
    projectId: 'auradb-21288',
    storageBucket: 'auradb-21288.firebasestorage.app',
    iosClientId: '935482127807-pdcpof30jr7doeg3tnfo7mvh8lp4bv38.apps.googleusercontent.com',
    iosBundleId: 'com.example.aurame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMNfTlo8wNiQevo509DuB1-2CNtyu8vWQ',
    appId: '1:935482127807:ios:0d2a5a00e2db12603f5d0a',
    messagingSenderId: '935482127807',
    projectId: 'auradb-21288',
    storageBucket: 'auradb-21288.firebasestorage.app',
    iosClientId: '935482127807-pdcpof30jr7doeg3tnfo7mvh8lp4bv38.apps.googleusercontent.com',
    iosBundleId: 'com.example.aurame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOIn4tAWtmTwstQx5swxaYLoWAaBs_tpE',
    appId: '1:935482127807:web:80e61c20b9028f413f5d0a',
    messagingSenderId: '935482127807',
    projectId: 'auradb-21288',
    authDomain: 'auradb-21288.firebaseapp.com',
    storageBucket: 'auradb-21288.firebasestorage.app',
    measurementId: 'G-1KJRM7SNLX',
  );
}
